--[[ ******************************************************************************
 My custom flash sensor tracer type ( Based on wire rangers )
****************************************************************************** ]]--

local DSC = E2Helper.Descriptions
local act = {"Returns","Adds","Removes","Updates","Samples"}
local xfs, par = "flash sensor", {"attachment entity", "origin position", "direction vector", "length distance"}
DSC["noFSensor()"] = act[1].." invalid "..xfs.." object"
DSC["setFSensor(e:vvn)"] = act[1].." "..xfs.." local to the entity by "..par[2]..", "..par[3]..", "..par[4]
DSC["newFSensor(vvn)"] = act[1].." "..xfs.." relative to the world by "..par[2]..", "..par[3]..", "..par[4]
DSC["setFSensor(e:vv)"] = act[1].." "..xfs.." local to the entity by "..par[2]..", "..par[3]..", "..par[4].. " from "..par[3]
DSC["newFSensor(vv)"] = act[1].." "..xfs.." relative to the world by "..par[2]..", "..par[3]..", "..par[4].. " from "..par[3]
DSC["setFSensor(e:vn)"] = act[1].." "..xfs.." relative to the entity by "..par[2]..", "..par[3].. " from up, "..par[4]
DSC["newFSensor(vn)"] = act[1].." "..xfs.." relative to the world by "..par[2]..", "..par[3].. " from up, "..par[4]
DSC["setFSensor(e:v)"] = act[1].." "..xfs.." local to the entity by "..par[2]..", zero "..par[3]..", zero "..par[4]
DSC["newFSensor(v)"] = act[1].." "..xfs.." relative to the world by "..par[2]..", zero "..par[3]..", zero "..par[4]
DSC["setFSensor(e:n)"] = act[1].." "..xfs.." relative to the entity by "..par[4]..", "..par[3]..", zero "..par[4]
DSC["newFSensor(n)"] = act[1].." "..xfs.." relative to the world by "..par[4]..", "..par[3]..", zero "..par[4]
DSC["setFSensor(e:)"] = act[1].." "..xfs.." local to the entity by zero "..par[2]..", zero "..par[3]..", zero "..par[4]
DSC["newFSensor()"] = act[1].." "..xfs.." relative to the world by zero "..par[2]..", zero "..par[3]..", zero "..par[4]
DSC["sumFSensors()"] = act[1].." the used "..xfs.." count"
DSC["maxFSensors()"] = act[1].." the upper "..xfs.." count"
DSC["remSelf(xfs:)"] = act[3].." the "..xfs.." from the list"
DSC["getCopy(xfs:)"] = act[1].." "..xfs.." copy instance of the current object"
DSC["addEntityHitSkip(xfs:e)"] = act[2].." the entity to the "..xfs.." internal ignore hit list"
DSC["remEntityHitSkip(xfs:e)"] = act[3].." the entity from the "..xfs.." internal ignore hit list"
DSC["addEntityHitOnly(xfs:e)"] = act[2].." the entity to the "..xfs.." internal only hit list"
DSC["remEntityHitOnly(xfs:e)"] = act[3].." the entity from the "..xfs.." internal only hit list"
DSC["remHit(xfs:)"] = act[3].." all the options from the "..xfs.." internal hit preferences"
DSC["remHit(xfs:s)"] = act[3].." the option from the "..xfs.." internal hit preferences"
DSC["addHitSkip(xfs:sn)"] = act[2].." the option to the "..xfs.." internal ignore hit list"
DSC["remHitSkip(xfs:sn)"] = act[3].." the option from the "..xfs.." internal ignore hit list"
DSC["addHitOnly(xfs:sn)"] = act[2].." the option to the "..xfs.." internal hit only list"
DSC["remHitOnly(xfs:sn)"] = act[3].." the option from the "..xfs.." internal only hit list"
DSC["addHitSkip(xfs:ss)"] = act[2].." the option to the "..xfs.." internal ignore hit list"
DSC["remHitSkip(xfs:ss)"] = act[3].." the option from the "..xfs.." internal ignore hit list"
DSC["addHitOnly(xfs:ss)"] = act[2].." the option to the "..xfs.." internal hit only list"
DSC["remHitOnly(xfs:ss)"] = act[3].." the option from the "..xfs.." internal only hit list"
DSC["getAttachEntity(xfs:)"] = act[1].." the attachment entity of the "..xfs
DSC["remAttachEntity(xfs:)"] = act[3].." the attachment entity of the "..xfs
DSC["setAttachEntity(xfs:e)"] = act[4].." the attachment entity of the "..xfs
DSC["getOrigin(xfs:)"] = act[1].." "..xfs.." "..par[2]
DSC["getOriginLocal(xfs:)"] = act[1].." "..xfs.." world "..par[2].." converted to "..par[1].." local axis"
DSC["getOriginLocal(xfs:e)"] = act[1].." "..xfs.." world "..par[2].." converted to entity local axis"
DSC["getOriginLocal(xfs:va)"] = act[1].." "..xfs.." world "..par[2].." converted to position/angle local axis"
DSC["getOriginWorld(xfs:)"] = act[1].." "..xfs.." local "..par[2].." converted to "..par[1].." world axis"
DSC["getOriginWorld(xfs:e)"] = act[1].." "..xfs.." local "..par[2].." converted to entity world axis"
DSC["getOriginWorld(xfs:va)"] = act[1].." "..xfs.." local "..par[2].." converted to position/angle world axis"
DSC["setOrigin(xfs:v)"] = act[4].." the "..xfs.." "..par[2]
DSC["getDirection(xfs:)"] = act[1].." "..xfs.." "..par[3]
DSC["getDirectionLocal(xfs:)"] = act[1].." "..xfs.." world "..par[3].." converted to "..par[1].." local axis"
DSC["getDirectionLocal(xfs:e)"] = act[1].." "..xfs.." world "..par[3].." converted to entity local axis"
DSC["getDirectionLocal(xfs:a)"] = act[1].." "..xfs.." world "..par[3].." converted to angle local axis"
DSC["getDirectionWorld(xfs:)"] = act[1].." "..xfs.." local "..par[3].." converted to "..par[1].." world axis"
DSC["getDirectionWorld(xfs:e)"] = act[1].." "..xfs.." local "..par[3].." converted to entity world axis"
DSC["getDirectionWorld(xfs:a)"] = act[1].." "..xfs.." local "..par[3].." converted to angle world axis"
DSC["setDirection(xfs:v)"] = act[4].." the "..xfs.." "..par[3]
DSC["getLength(xfs:)"] = act[1].." "..xfs.." "..par[4]
DSC["setLength(xfs:n)"] = act[4].." "..xfs.." "..par[4]
DSC["getMask(xfs:)"] = act[1].." "..xfs.." trace hit mask enums MASK"
DSC["setMask(xfs:n)"] = act[4].." "..xfs.." trace hit mask enums MASK"
DSC["getStart(xfs:)"] = act[1].." "..xfs.." trace start poisition sent to trace-line"
DSC["getStop(xfs:)"] = act[1].." "..xfs.." trace stop poisition sent to trace-line"
DSC["getCollisionGroup(xfs:)"] = act[1].." "..xfs.." trace collision group enums COLLISION_GROUP"
DSC["setCollisionGroup(xfs:n)"] = act[4].." "..xfs.." trace collision group enums COLLISION_GROUP"
DSC["isIgnoreWorld(xfs:)"] = act[1].." the "..xfs.." trace `IgnoreWorld` flag"
DSC["setIsIgnoreWorld(xfs:n)"] = act[4].." the "..xfs.." trace `IgnoreWorld` flag"
DSC["smpLocal(xfs:)"] = act[5].." the "..xfs.." and updates the trace-result according to "..par[1].." local axis"
DSC["smpLocal(xfs:e)"] = act[5].." the "..xfs.." and updates the trace-result according to argument entity"
DSC["smpLocal(xfs:va)"] = act[5].." the "..xfs.." and updates the trace-result according to argument position and angle"
DSC["smpWorld(xfs:)"] = act[5].." the "..xfs.." and updates the trace-result according to the world axis"
DSC["isHitNoDraw(xfs:)"] = act[1].." the "..xfs.." trace-result `HitNoDraw` flag"
DSC["isHitNonWorld(xfs:)"] = act[1].." the "..xfs.." trace-result `HitNonWorld` flag"
DSC["isHit(xfs:)"] = act[1].." the "..xfs.." trace-result `Hit` flag"
DSC["isHitSky(xfs:)"] = act[1].." the "..xfs.." trace-result `HitSky` flag"
DSC["isHitWorld(xfs:)"] = act[1].." the "..xfs.." trace-result `HitWorld` flag"
DSC["getHitBox(xfs:)"] = act[1].." the "..xfs.." trace-result `HitBox` number"
DSC["getMatType(xfs:)"] = act[1].." the "..xfs.." trace-result `MatType` material type number"
DSC["getHitGroup(xfs:)"] = act[1].." the "..xfs.." trace-result `HitGroup` group ID number"
DSC["getHitPos(xfs:)"] = act[1].." the "..xfs.." trace-result `HitPos` location vector"
DSC["getHitNormal(xfs:)"] = act[1].." "..xfs.." the trace-result surface `HitNormal` vector"
DSC["getNormal(xfs:)"] = act[1].." the "..xfs.." trace-result `Normal` aim vector"
DSC["getHitTexture(xfs:)"] = act[1].." the "..xfs.." trace-result `HitTexture` string"
DSC["getStartPos(xfs:)"] = act[1].." the "..xfs.." trace-result `StartPos` vector"
DSC["getSurfaceProps(xfs:)"] = act[1].." the "..xfs.." trace-result `SurfaceProps` ID type number"
DSC["getSurfacePropsName(xfs:)"] = act[1].." the "..xfs.." trace-result `SurfaceProps` ID type name string"
DSC["getPhysicsBone(xfs:)"] = act[1].." the "..xfs.." trace-result `PhysicsBone` ID number"
DSC["getFraction(xfs:)"] = act[1].." the "..xfs.." trace-result `Fraction` in the interval [0-1] number"
DSC["getFractionLength(xfs:)"] = act[1].." the "..xfs.." trace-result `Fraction` multiplied by its "..par[4].." number"
DSC["isStartSolid(xfs:)"] = act[1].." the "..xfs.." trace-result `StartSolid` flag"
DSC["isAllSolid(xfs:)"] = act[1].." the "..xfs.." trace-result `AllSolid` flag"
DSC["getFractionLeftSolid(xfs:)"] = act[1].." the "..xfs.." trace-result `FractionLeftSolid` in the interval [0-1] number"
DSC["getFractionLeftSolidLength(xfs:)"] = act[1].." the "..xfs.." trace-result `FractionLeftSolid` multiplied by its "..par[4].." number"
DSC["getEntity(xfs:)"] = act[1].." the "..xfs.." trace-result `Entity` entity"
