---------------------------------
-- Derma HML tags for HML 1.0 --
---------------------------------
--
-- DO NOT EDIT!
--
-- Put custom tag definitions in lua files in this DIR instead!
-- Moggie100
--
--
-- Note: These should always return their children's draw context, or a string-type error message.
--       If they have NO children, then return their own draw context, followed by 'false' as a second arg
